import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={`antialiased`} >
        <header>
          <Link href="/" className="absolute top-4 left-4 flex items-center text-white px-4 py-2 rounded-full hover:bg-gray-800 transition duration-200">
            <span className="mr-2">&larr;</span> Back
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
