import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <div className="h-screen w-screen" style={{ backgroundImage: `url(/spacedust.jpg)`, backgroundSize: '100%', backgroundRepeat: 'no-repeat' }} >
        <header>
        </header>
        {children}
      </div>
  );
}
